# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hauptkontaktperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='bspw. Oberst, Kompanieführer', max_length=128, verbose_name='Position')),
                ('name', models.CharField(max_length=128, verbose_name='Vorname Name')),
                ('strasse', models.CharField(max_length=128)),
                ('plzort', models.CharField(max_length=128, verbose_name='PLZ Ort')),
                ('tel', models.CharField(max_length=128, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='E-Mail')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VISDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Vorname Name')),
                ('strasse', models.CharField(max_length=128)),
                ('plzort', models.CharField(max_length=128, verbose_name='PLZ Ort')),
                ('tel', models.CharField(max_length=128, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='E-Mail')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Verantwortlich für den Inhalt',
            },
        ),
        migrations.CreateModel(
            name='Zweitkontaktperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='bspw. Oberst, Kompanieführer', max_length=128, verbose_name='Position')),
                ('name', models.CharField(max_length=128, verbose_name='Vorname Name')),
                ('strasse', models.CharField(max_length=128)),
                ('plzort', models.CharField(max_length=128, verbose_name='PLZ Ort')),
                ('tel', models.CharField(max_length=128, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='E-Mail')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
