# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scms2.blocks
import seiten.blocks
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('seiten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeitenIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Ordner für Unterseiten',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='seite',
            name='kurztitel',
            field=models.CharField(blank=True, help_text='Kurzer Titel, der in Menus benutzt wird', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seite',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', scms2.blocks.HeadingBlock(classname='full title', group='Einfacher Text')), ('paragraph', scms2.blocks.Absatz(group='Einfacher Text')), ('quote', scms2.blocks.QuoteBlock(group='Spezieller Text')), ('image', wagtail.wagtailcore.blocks.StructBlock((('img', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('align', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('LINKS', 'links'), ('LINKS_SM', 'links, kleiner'), ('RECHTS', 'rechts'), ('RECHTS_SM', 'rechts, kleiner'), ('FULL', 'ganze Breite')], help_text='Wie soll das Bild angezeigt werden?', label='Ausrichtung und Größe')), ('beschriftung', wagtail.wagtailcore.blocks.TextBlock(help_text='Dieser Text wird unterhalb des Bilds eingefügt', required=False))), group='Fotos und Bilder')), ('album', wagtail.wagtailcore.blocks.StructBlock((('album', wagtail.wagtailcore.blocks.PageChooserBlock(label='Fotoalbum auswählen', required=True, target_model=['fotoalben.Fotoalbum'])), ('show_as', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('single', 'Einzelnes Bild'), ('carousel', 'Bilderkarussell')], help_text='Wie soll das Fotoalbum angezeigt werden?', label='Anzeige als')), ('auto_caption', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Soll die Bildunterschrift automatisch aus den Informationen für das Bild generiert werden?', label='Automatische Bildunterschrift', required=False)), ('caption', wagtail.wagtailcore.blocks.CharBlock(label='Manuelle Bildunterschrift', max_length=256, required=False)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('full', 'Volle Breite'), ('left_sm', 'klein, links im Text'), ('left_med', 'mittelgroß, links im Text'), ('right_sm', 'klein, rechts im Text'), ('right_med', 'mittelgroß, rechts im Text')], help_text='Bei Anzeige als Einzelbild: Wo soll das Bild platziert werden?', required=False, verbose_name='Anzeigeoptionen')), ('link', wagtail.wagtailcore.blocks.BooleanBlock(default=True, help_text='Link zum Album einfügen?', required=False, verbose_name='Link'))), group='Fotos und Bilder')), ('bilderliste', scms2.blocks.ImgListBlock(group='Fotos und Bilder', label='Fotoliste')), ('table', wagtail.contrib.table_block.blocks.TableBlock(group='Einfacher Text', label='Tabelle')), ('komplexe_liste', scms2.blocks.ComplexListBlock(group='Spezieller Text')), ('img_citation', wagtail.wagtailcore.blocks.StructBlock((('img', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bild', required=True)), ('zitat', wagtail.wagtailcore.blocks.CharBlock(label='Text', max_length=256, required=True))), group='Fotos und Bilder')), ('map', scms2.blocks.OpenStreetMapBlock(group='spezielle Inhalte')), ('youtube_video', wagtail.wagtailembeds.blocks.EmbedBlock(group='Videos')), ('local_video', wagtail.wagtailcore.blocks.StructBlock((('standard', wagtail.wagtaildocs.blocks.DocumentChooserBlock(help_text='Video-Datei für standarkonforme Browser (Container webm, Codec: V8.0, Audio: Ogg)', label='Standard-Datei')), ('alt1', wagtail.wagtaildocs.blocks.DocumentChooserBlock(help_text='alternative Video-Datei (bspw. für Apple-Safari: Container mp4, Codec: H.264, Audio)', label='Alternative 1', required=False)), ('alt2', wagtail.wagtaildocs.blocks.DocumentChooserBlock(help_text='alternative Video-Datei (bspw. für Internet-Explorer)', label='Alternative 2', required=False))), group='Videos')), ('video_karussell', scms2.blocks.VideoCarouselBlock(group='Videos')), ('strophe', scms2.blocks.Strophe(group='Spezieller Text')), ('adresse', scms2.blocks.Adresse(group='Spezieller Text')), ('sitemap', scms2.blocks.SitemapBlock(group='spezielle Inhalte')), ('toc', seiten.blocks.TOCBlock(group='spezielle Inhalte'))), verbose_name='Seiteninhalt'),
        ),
    ]
