# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('datum', models.DateField()),
                ('uhrzeit', models.TimeField(blank=True, null=True)),
                ('beschreibung', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TerminListe',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('einleitung', models.TextField(blank=True, help_text=' Kurze Einleitung, die zu Beginn der Auflistungsseite erscheint.', max_length=1024, null=True)),
                ('vergangene_termine', models.BooleanField(default=False, help_text='Sollen vergangene Termine angezeigt werden?', verbose_name='Vergangene Termine anzeigen?')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
