# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminliste',
            options={'verbose_name': 'Liste der Termine'},
        ),
        migrations.AddField(
            model_name='termin',
            name='enddatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termin',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminliste',
            name='einleitung',
            field=models.TextField(blank=True, help_text='Kurze Einleitung, die zu Beginn der Auflistungsseite erscheint.', max_length=1024, null=True),
        ),
    ]
