# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startseite'},
        ),
    ]
