# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('fotoalben', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoalbumCollection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Sammlung von Fotoalben',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FotoalbumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('promote', models.BooleanField(default=False, verbose_name='Dieses Bild als Titelbild verwenden')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FotoalbumIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sort', models.BooleanField(default=True, help_text='Die Inhalte werden absteigend alphabetisch sortiert. Sonnvoll für Jahreszahlen mit neuesten Jahren zuerst.', verbose_name='Inhalte sortieren?')),
            ],
            options={
                'verbose_name': 'Liste aller Fotoalben',
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='FotoalbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fotoalbum',
            name='bilder',
        ),
        migrations.AddField(
            model_name='fotoalbum',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection'),
        ),
        migrations.AddField(
            model_name='fotoalbum',
            name='datum',
            field=models.DateField(blank=True, help_text='Wenn dieses Feld freigelassen wird, wird das aktuelle Datum verwendet (außer, es wird eine spätere Veröffentlichung eingestellt).', null=True, verbose_name='angezeigtes Datum der Veröffentlichung'),
        ),
        migrations.AddField(
            model_name='fotoalbumtag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='fotoalben.Fotoalbum'),
        ),
        migrations.AddField(
            model_name='fotoalbumtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotoalben_fotoalbumtag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='fotoalbumimages',
            name='images',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='verlinkte_bilder', to='fotoalben.Fotoalbum'),
        ),
        migrations.AddField(
            model_name='fotoalbumimages',
            name='linked_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='enthaltenes Bild'),
        ),
        migrations.AddField(
            model_name='fotoalbum',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='fotoalben.FotoalbumTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
